//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public software()
        {
            this.equipos_software = new HashSet<equipos_software>();
        }
    
        public int id_softaware { get; set; }
        public string nom_software { get; set; }
        public string cod_licencia { get; set; }
        public string tipo_licencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipos_software> equipos_software { get; set; }
    }
}
